---
# task for hadenlabs.nginx

- name: Install packages via pip ntp
  become: true
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when: _ntp_pip_packages is defined
  with_items: "{{ _ntp_pip_packges | default({}) }}"
